
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztzlarsaoqbzophivmoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0emxhcnNhb3Fiem9waGl2bW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzAyNTUsImV4cCI6MjA1ODYwNjI1NX0.VCuPfLvYohlUrQCS_833pSQ8ESC_GuWtK0aYXwQ07Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storageKey: 'mental-pitch-auth-token', // Use the same storage key
    storage: localStorage
  }
});
